### ISSUE TITLE
bug: RWE-yadage crashes on string-like resources

### ISSUE THREAD

**Issue by lukasheinrich** [reanahub/reana-workflow-engine-yadage#188]
the resource handling in RWE-yadgae assumes the resource entries are dicts however this was an additoin from the REANA team. originally in yadage these are strings. RWE-yadage should at least not crash on string-like resource definitins.

example:

```
  environment:
    environment_type: docker-encapsulated
    image: busybox
    imagetag: latest
    resources:
      - foo
```
